// Generated by `wit-bindgen` 0.21.0. DO NOT EDIT!
#ifndef __BINDINGS_CALCULATOR_H
#define __BINDINGS_CALCULATOR_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

typedef uint8_t exports_vscode_example_types_operation_t;

#define EXPORTS_VSCODE_EXAMPLE_TYPES_OPERATION_ADD 0
#define EXPORTS_VSCODE_EXAMPLE_TYPES_OPERATION_SUB 1
#define EXPORTS_VSCODE_EXAMPLE_TYPES_OPERATION_MUL 2
#define EXPORTS_VSCODE_EXAMPLE_TYPES_OPERATION_DIV 3

typedef struct exports_vscode_example_types_own_machine_t {
  int32_t __handle;
} exports_vscode_example_types_own_machine_t;

typedef struct exports_vscode_example_types_machine_t exports_vscode_example_types_machine_t;

typedef exports_vscode_example_types_machine_t* exports_vscode_example_types_borrow_machine_t;

// Exported Functions from `vscode:example/types`
exports_vscode_example_types_own_machine_t exports_vscode_example_types_constructor_machine(uint32_t left, uint32_t right, exports_vscode_example_types_operation_t operation);
uint32_t exports_vscode_example_types_method_machine_execute(exports_vscode_example_types_borrow_machine_t self);

// Helper Functions

extern void exports_vscode_example_types_machine_drop_own(exports_vscode_example_types_own_machine_t handle);

extern exports_vscode_example_types_own_machine_t exports_vscode_example_types_machine_new(exports_vscode_example_types_machine_t *rep);
extern exports_vscode_example_types_machine_t* exports_vscode_example_types_machine_rep(exports_vscode_example_types_own_machine_t handle);
void exports_vscode_example_types_machine_destructor(exports_vscode_example_types_machine_t *rep);


#ifdef __cplusplus
}
#endif
#endif
